apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  label:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replica: 3
  template:
    metadata:
       name: nginx-pod
       labels:
           app: myapp
           environment: production
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
         